import type { Role, SubTopic, Tier } from "@/types";

export type DemoUserSeed = {
  username: string;
  display_name: string;
  tier: Tier;
  role: Exclude<Role, "admin">;
  current_hp: number;
  utility_tokens: number;
};

export type DemoPostSeed = {
  title: string;
  body: string;
  sub_topic: SubTopic;
  current_health: number;
  authorUsername: string;
  hoursAgo: number;
};

export const DEMO_USERS: DemoUserSeed[] = [
  {
    username: "demo_vale_hart",
    display_name: "Vale Hart",
    tier: "Bronze",
    role: "member",
    current_hp: 52,
    utility_tokens: 70,
  },
  {
    username: "demo_nara_quinn",
    display_name: "Nara Quinn",
    tier: "Bronze",
    role: "member",
    current_hp: 74,
    utility_tokens: 85,
  },
  {
    username: "demo_elio_voss",
    display_name: "Elio Voss",
    tier: "Bronze",
    role: "elite",
    current_hp: 91,
    utility_tokens: 60,
  },
  {
    username: "demo_kira_moss",
    display_name: "Kira Moss",
    tier: "Bronze",
    role: "member",
    current_hp: 63,
    utility_tokens: 78,
  },
  {
    username: "demo_mira_chen",
    display_name: "Mira Chen",
    tier: "Silver",
    role: "member",
    current_hp: 124,
    utility_tokens: 90,
  },
  {
    username: "demo_jonas_reed",
    display_name: "Jonas Reed",
    tier: "Silver",
    role: "member",
    current_hp: 158,
    utility_tokens: 110,
  },
  {
    username: "demo_priya_shah",
    display_name: "Priya Shah",
    tier: "Silver",
    role: "elite",
    current_hp: 181,
    utility_tokens: 95,
  },
  {
    username: "demo_rafael_dunn",
    display_name: "Rafael Dunn",
    tier: "Silver",
    role: "member",
    current_hp: 146,
    utility_tokens: 88,
  },
  {
    username: "demo_owen_blake",
    display_name: "Owen Blake",
    tier: "Gold",
    role: "member",
    current_hp: 236,
    utility_tokens: 100,
  },
  {
    username: "demo_sasha_kline",
    display_name: "Sasha Kline",
    tier: "Gold",
    role: "member",
    current_hp: 279,
    utility_tokens: 120,
  },
  {
    username: "demo_helen_ortiz",
    display_name: "Helen Ortiz",
    tier: "Gold",
    role: "elite",
    current_hp: 318,
    utility_tokens: 80,
  },
  {
    username: "demo_amina_cole",
    display_name: "Amina Cole",
    tier: "Gold",
    role: "member",
    current_hp: 254,
    utility_tokens: 102,
  },
  {
    username: "demo_marcus_dale",
    display_name: "Marcus Dale",
    tier: "Platinum",
    role: "member",
    current_hp: 372,
    utility_tokens: 130,
  },
  {
    username: "demo_yuna_park",
    display_name: "Yuna Park",
    tier: "Platinum",
    role: "member",
    current_hp: 448,
    utility_tokens: 140,
  },
  {
    username: "demo_theo_nilsen",
    display_name: "Theo Nilsen",
    tier: "Platinum",
    role: "elite",
    current_hp: 511,
    utility_tokens: 105,
  },
  {
    username: "demo_lev_okada",
    display_name: "Lev Okada",
    tier: "Platinum",
    role: "member",
    current_hp: 401,
    utility_tokens: 118,
  },
  {
    username: "demo_irene_wahl",
    display_name: "Irene Wahl",
    tier: "Masters",
    role: "member",
    current_hp: 646,
    utility_tokens: 160,
  },
  {
    username: "demo_cyrus_ade",
    display_name: "Cyrus Ade",
    tier: "Masters",
    role: "member",
    current_hp: 762,
    utility_tokens: 175,
  },
  {
    username: "demo_lina_moreau",
    display_name: "Lina Moreau",
    tier: "Masters",
    role: "elite",
    current_hp: 891,
    utility_tokens: 150,
  },
  {
    username: "demo_nora_weiss",
    display_name: "Nora Weiss",
    tier: "Masters",
    role: "elite",
    current_hp: 704,
    utility_tokens: 155,
  },
];

export const DEMO_POSTS: DemoPostSeed[] = [
  {
    title: "UnitedHealth utilization reset: the multiple is the risk, not membership",
    body: "Membership trends remain intact. The debate is medical-cost trend and how long the Street will pay a premium multiple while utilization normalizes. We would rather own the name on a 5–7% drawdown than chase the first print that looks clean. Watch Medicare Advantage risk scores and outpatient intensity; if both stabilize together, the earnings trough is closer than the tape implies. Position as a quality compounder, not a momentum health-care trade.",
    sub_topic: "Healthcare",
    current_health: 118,
    authorUsername: "demo_lina_moreau",
    hoursAgo: 4,
  },
  {
    title: "Eli Lilly obesity franchise: capacity, net price, and the 2027 cliff",
    body: "Demand is not the question. Manufacturing scale and net pricing are. The bull case needs another step-up in incretin capacity without a disorderly price war in the next cohort of oral competitors. We model a slower volume ramp and still get an attractive free-cash-yield by 2027 if the franchise holds share in the high-value indication. The risk is not a demand air-pocket; it is a two-year period where capex stays elevated and the multiple compresses anyway.",
    sub_topic: "Healthcare",
    current_health: 44,
    authorUsername: "demo_helen_ortiz",
    hoursAgo: 11,
  },
  {
    title: "Hospital labor has peaked; regional systems are the cleaner expression",
    body: "Contract labor and wage inflation look rolled over in the better-run regional systems. National chains still carry integration and payer-mix noise. We prefer operators with a single-state density story and a credible ambulatory shift. If admissions stay flattish, margin recovery comes from mix and agency-spend reversal, not top-line heroics. This is a 12-month operating-leverage tape, not a volume-recovery tape.",
    sub_topic: "Healthcare",
    current_health: 76,
    authorUsername: "demo_mira_chen",
    hoursAgo: 20,
  },
  {
    title: "Novo Nordisk: the compounding risk is manufacturing, not prescriptions",
    body: "Prescription momentum remains exceptional. The constraint is still fill rates and the pace at which new capacity is qualified. We would fade narrative spikes around any single-quarter beat and accumulate on manufacturing slippage. The franchise can absorb a slower script trend; it cannot absorb a loss of confidence in supply. Treat this as an industrial-scale problem wearing a health-care multiple.",
    sub_topic: "Healthcare",
    current_health: 22,
    authorUsername: "demo_nara_quinn",
    hoursAgo: 31,
  },
  {
    title: "Intuitive Surgical: procedure mix is the multiple; capital placement is the tell",
    body: "System placements get the headlines. The equity story is procedure mix, utilization per installed robot, and whether soft-tissue share gains keep compounding after the easy hospital conversions. We would own a pause in placements if utilization and attach stay firm. We would not own a placement beat that is just channel fill. This is a razor-and-blade franchise. Underwrite the blade.",
    sub_topic: "Healthcare",
    current_health: 97,
    authorUsername: "demo_nora_weiss",
    hoursAgo: 17,
  },
  {
    title: "Humana: the MA rate notice is the stock; membership is the noise",
    body: "Medicare Advantage margin recovery is a two-year underwriting problem, not a one-print event. The rate notice, risk-score coding, and benefit design will decide whether 2026 earnings are a trough or a trap. We would rather be early on a cleaner rate year than chase a membership print that was bought with benefits. Size it as a mean-reversion in medical-cost ratio, with a hard stop if coding integrity becomes a political story.",
    sub_topic: "Healthcare",
    current_health: 33,
    authorUsername: "demo_rafael_dunn",
    hoursAgo: 39,
  },
  {
    title: "Danaher bioprocess: destocking is over; the multiple still needs volume",
    body: "The inventory air-pocket in bioprocess tools looks behind us. That is necessary, not sufficient. The stock needs a second year of volume recovery in mAbs and a cleaner mix in genomics before we pay a peak-cycle multiple again. Prefer this to a basket of life-science tools because the installed base and recurring consumables are real. Do not treat the first restock quarter as a new regime.",
    sub_topic: "Healthcare",
    current_health: 61,
    authorUsername: "demo_amina_cole",
    hoursAgo: 46,
  },
  {
    title: "Vertex: CF cash still funds the pipeline; the market is pricing a second franchise",
    body: "The cystic-fibrosis annuity remains one of the cleanest cash engines in large-cap biotech. The debate is whether pain, kidney, or the next gene-editing program can become a second pillar before the Street gets impatient. We would rather own a missed pipeline print than a multiple that already assumes two franchises. Keep the position as a cash-flow compounder with optionality, not as a binary catalyst book.",
    sub_topic: "Healthcare",
    current_health: 84,
    authorUsername: "demo_kira_moss",
    hoursAgo: 52,
  },
  {
    title: "JPMorgan NII: deposit beta is the only number that matters from here",
    body: "Loan growth is fine. Fee income is fine. The stock will trade the path of deposit costs versus the implied forward curve. If beta stays contained as cuts arrive, NII is more resilient than a simple peak-rate fade suggests. We are not paying for a re-acceleration in dealmaking; we are paying for a balance sheet that can defend the dividend and still grow tangible book. Prefer this over a basket of regionals until the deposit story is cleaner.",
    sub_topic: "Banks",
    current_health: 132,
    authorUsername: "demo_cyrus_ade",
    hoursAgo: 6,
  },
  {
    title: "European bank capital return is real; the risk is political, not credit",
    body: "CET1 is excess, not theoretical. Buybacks and special dividends are the equity story. Credit quality is not the near-term break. The break is a political intervention on distributions or a sudden change in the sovereign-bank loop. We would own the surplus-capital names with already-announced return programs and avoid the ones that still need a regulatory blessing every quarter. This is a cash-return book with a policy tail.",
    sub_topic: "Banks",
    current_health: 58,
    authorUsername: "demo_theo_nilsen",
    hoursAgo: 15,
  },
  {
    title: "US regionals: CRE is in the price; fee income is not",
    body: "Office CRE has been marked in the better disclosures. The next distinction is who can grow treasury-management and wealth fees while the securities book still rolls. We want cheap deposits, a contained office book, and a fee line that is not just mortgage. The cheap names that are only cheap on a tangible-book print are value traps if they cannot generate capital internally. Underwrite the operating account, not the office footnote.",
    sub_topic: "Banks",
    current_health: 36,
    authorUsername: "demo_jonas_reed",
    hoursAgo: 27,
  },
  {
    title: "Bank of America: the consumer deposit franchise is the duration hedge",
    body: "The stock is a leveraged claim on the path of deposit costs and the securities book. If the consumer franchise keeps cheap operating balances, NII can defend better than a simple peak-rate fade. If those balances migrate, the AOCI hangover lasts longer than the Street wants. We would own it as a high-quality balance-sheet compounder on a deposit-beta miss, not as a trading-bank proxy on a curve steepener.",
    sub_topic: "Banks",
    current_health: 109,
    authorUsername: "demo_lev_okada",
    hoursAgo: 12,
  },
  {
    title: "Goldman Sachs: advisory is the option; the multiple needs FICC discipline",
    body: "A recovery in M&A is real optionality. It is not a reason to pay a peak investment-bank multiple if FICC remains the earnings ballast. We want evidence that the platform can hold compensation ratios and grow wealth without another capital-markets air pocket. Prefer this on a print that looks boring in trading and better in advisory, not the reverse. Size it as a cycle, with a hard stop if leverage creeps back into the funding story.",
    sub_topic: "Banks",
    current_health: 49,
    authorUsername: "demo_sasha_kline",
    hoursAgo: 34,
  },
  {
    title: "Wells Fargo: the asset-cap hangover is fading; the franchise still has to earn it",
    body: "Regulatory relief is a necessary condition, not a thesis. The equity works if the consumer and commercial franchises can grow loans and fees without re-introducing the conduct risk that created the cap. We would rather own a slow, clean capital-return year than a growth re-rating that assumes the bank is already a peer of JPM. Underwrite the operating account and the expense ratio. Fade the first 'unleashed' headline.",
    sub_topic: "Banks",
    current_health: 71,
    authorUsername: "demo_priya_shah",
    hoursAgo: 41,
  },
  {
    title: "Charles Schwab: cash sorting is the residual risk, not the franchise",
    body: "The client franchise is intact. The stock still trades the last mile of cash sorting versus the securities book. If insured-deposit sweeps stabilize and NII troughs, the multiple can re-rate as a quality compounder. If sorting has another leg, the earnings trough is later than the tape wants. We would accumulate on a sorting scare, not on a relief rally that assumes the mix shift is finished.",
    sub_topic: "Banks",
    current_health: 88,
    authorUsername: "demo_owen_blake",
    hoursAgo: 23,
  },
  {
    title: "Morgan Stanley: wealth is the multiple; institutional is the variance",
    body: "The wealth and asset-management mix is why this name deserves a different multiple than a pure trading book. Institutional securities will keep injecting quarter-to-quarter noise. We would own a weak institutional print if wealth net new assets and fee-based mix stay on trend. We would not own a trading beat that the market treats as a new run-rate. This is a wealth compounder with a capital-markets overlay. Price it that way.",
    sub_topic: "Banks",
    current_health: 26,
    authorUsername: "demo_vale_hart",
    hoursAgo: 58,
  },
  {
    title: "CrowdStrike: platform attach is the bull case, not endpoint share",
    body: "Endpoint share is already in the multiple. The next 24 months are about module attach, net retention, and whether the platform can keep displacing point products after a noisy incident year. We would own it as a platform-expansion story with a higher bar for execution, not as a clean-growth multiple. If attach stalls, the stock becomes a high-quality compounder at a lower number. That is still interesting. Chasing a re-rating on logos alone is not.",
    sub_topic: "Cybersecurity",
    current_health: 101,
    authorUsername: "demo_irene_wahl",
    hoursAgo: 8,
  },
  {
    title: "Palo Alto: SASE mix versus a crowded network-security tape",
    body: "The strategic case is the mix shift into SASE and a tighter software attachment story. The tactical case is that every large-cap network-security name is selling a version of the same consolidation pitch. We want evidence of deal size expansion, not just billings optics. Prefer this on a pullback when the market treats it as a hardware leftover. Do not pay a software multiple for a transition that still has to be proven in the next two prints.",
    sub_topic: "Cybersecurity",
    current_health: 47,
    authorUsername: "demo_sasha_kline",
    hoursAgo: 18,
  },
  {
    title: "Cyber budgets are not discretionary this cycle; buy seat-expansion vendors",
    body: "Boards are not cutting the cyber line the way they cut marketing. The better vendors are still expanding seats and modules inside existing accounts. That is a different underwriting problem than a new-logo land-grab. We would rather own the names with demonstrated net-retention and a path to platform pricing than the ones that need a new category to justify the print. This is a maintenance-capex industry wearing a growth multiple. Underwrite it that way.",
    sub_topic: "Cybersecurity",
    current_health: 83,
    authorUsername: "demo_priya_shah",
    hoursAgo: 22,
  },
  {
    title: "Cyber insurance pricing is the leading indicator for vendor spend",
    body: "When insurance pricing tightens, control requirements follow, and that shows up in vendor attach with a lag. We are watching primary cyber-insurance rates and claims frequency as a cleaner tell than CIO surveys. If pricing stays firm, the spending cycle has another year. If it breaks, the first cut is not the platform vendor; it is the long tail of point tools. Position accordingly: own the control plane, not the catalog.",
    sub_topic: "Cybersecurity",
    current_health: 19,
    authorUsername: "demo_elio_voss",
    hoursAgo: 40,
  },
  {
    title: "Zscaler: zero-trust is the category; the multiple needs remaining performance",
    body: "The architectural case is intact. The stock will trade remaining performance obligation and calculated billings more than logo adds. We want to see larger deal sizes and a cleaner path to platform attach in data protection, not just a re-acceleration narrative. Prefer this on a billings miss that does not break net retention. Fade a beat that is only a timing shift in large deals. This is a platform story that still has to earn a software-scarcity multiple.",
    sub_topic: "Cybersecurity",
    current_health: 92,
    authorUsername: "demo_yuna_park",
    hoursAgo: 14,
  },
  {
    title: "Cloudflare: the edge is a real asset; the equity is still a duration trade",
    body: "Workers, security, and network services are a coherent platform. The multiple still assumes a long duration of high incremental margins. We would own a growth scare if large-customer net retention holds. We would not own a re-rating that treats every new product as already at scale. Underwrite the large-account motion and the mix of usage versus subscription. The edge is interesting. Paying any price for it is not.",
    sub_topic: "Cybersecurity",
    current_health: 54,
    authorUsername: "demo_amina_cole",
    hoursAgo: 36,
  },
  {
    title: "Okta: identity is strategic; the stock needs a cleaner execution year",
    body: "Identity is not going back to being a point tool. That does not automatically repair a multiple that has already paid for a platform. We want two clean prints on large-customer retention, a quieter security narrative, and evidence that workforce plus customer identity can be sold as one motion. Accumulate on an execution discount. Do not pay a category-leader multiple for a turnaround that is still one print away.",
    sub_topic: "Cybersecurity",
    current_health: 38,
    authorUsername: "demo_jonas_reed",
    hoursAgo: 49,
  },
  {
    title: "Fortinet: firewall refresh is late-cycle; SASE has to do the next work",
    body: "The installed base can still produce a refresh. That is a late-cycle earnings support, not a new growth regime. The equity needs a credible software and SASE mix so the multiple does not compress when product revenue cools. We would own a product miss if service attach and SASE bookings stay intact. We would not own a hardware beat that the market treats as a re-acceleration. This is a transition tape. Price the destination, not the last refresh.",
    sub_topic: "Cybersecurity",
    current_health: 67,
    authorUsername: "demo_marcus_dale",
    hoursAgo: 28,
  },
  {
    title: "Microsoft Azure: inference is a margin story before it is a revenue story",
    body: "The Azure print will keep looking noisy while training clusters and inference workloads move around. The investment question is whether incremental AI revenue drops through at a better margin than the last wave of consumption. We think it does, with a lag. That supports the multiple if capex discipline holds. It does not support paying any price for a single-quarter acceleration. Own it as the default enterprise distribution layer, not as a pure-play AI beta.",
    sub_topic: "Technology",
    current_health: 141,
    authorUsername: "demo_lina_moreau",
    hoursAgo: 3,
  },
  {
    title: "TSMC is the bottleneck equity; everything else is a derivative",
    body: "If you need one clean expression of the AI hardware cycle, it is still the foundry that can actually deliver leading-edge wafers. Downstream names are claims on the same scarce capacity with more customer and product risk. We would rather hold the bottleneck and finance the rest around it. The bear case is a sharper capex pause from the largest customers. Even then, the utilization math is better here than in most of the equipment tape.",
    sub_topic: "Technology",
    current_health: 88,
    authorUsername: "demo_yuna_park",
    hoursAgo: 13,
  },
  {
    title: "Apple services: the multiple needs net adds, not just installed base",
    body: "Services growth that is only price and mix will not hold this multiple if hardware units stay soft. We need to see net adds in the higher-value subscriptions, not just ARPU on a flat base. The stock can work as a cash-return vehicle either way. It cannot work as a growth compounder without a cleaner services unit story. We are patient, not reflexive buyers, until the next couple of prints separate price from participation.",
    sub_topic: "Technology",
    current_health: 41,
    authorUsername: "demo_owen_blake",
    hoursAgo: 25,
  },
  {
    title: "NVIDIA CUDA lock-in versus custom silicon: a 24-month debate, not a quarter",
    body: "Custom silicon will take share at the margin. That is not the same as breaking the software lock. The next two years are about how much inference moves off the general-purpose GPU and at what price. We would not run a binary short on that headline. We would also not treat every pullback as a gift if the largest customers start signaling a longer interpolation cycle. Size the position as a cycle, not as a religion.",
    sub_topic: "Technology",
    current_health: 29,
    authorUsername: "demo_vale_hart",
    hoursAgo: 38,
  },
  {
    title: "Broadcom: VMware conversion is the bridge; custom AI silicon is the option",
    body: "The near-term equity story is still the VMware customer conversion and the durability of the infrastructure software attach. Custom AI accelerators are real optionality, not the base case we will pay for twice. We would own a conversion scare if remaining performance and customer retention hold. We would not own a silicon headline that the market treats as already in the run-rate. This is a cash-return compounder with a second engine. Keep the second engine unpriced.",
    sub_topic: "Technology",
    current_health: 113,
    authorUsername: "demo_theo_nilsen",
    hoursAgo: 9,
  },
  {
    title: "Amazon AWS: the re-acceleration has to show up in operating margin, not just run-rate",
    body: "A firmer AWS growth print is necessary. It is not the whole thesis. Incremental AI and migration workloads have to drop through at a margin that can fund the capex cycle. We would accumulate on a growth miss that keeps margin discipline. We would fade a run-rate beat that is bought with price or mix that does not last. Own the distribution layer of enterprise compute. Do not treat every AI announcement as already in the earnings power.",
    sub_topic: "Technology",
    current_health: 78,
    authorUsername: "demo_helen_ortiz",
    hoursAgo: 21,
  },
  {
    title: "ASML: EUV intensity is the cycle; High-NA is the duration argument",
    body: "The installed-base service annuity is the ballast. The equity duration is High-NA adoption and whether leading-edge customers keep raising EUV intensity per wafer. We would own a booking air-pocket if the technology roadmap is intact. We would not own a China-export headline as if it were a new structural growth story. This is a bottleneck tool name. Size it as a cycle with a high-quality installed base, not as a straight-line AI compounder.",
    sub_topic: "Technology",
    current_health: 56,
    authorUsername: "demo_lev_okada",
    hoursAgo: 33,
  },
  {
    title: "Meta: the ad cycle is intact; the multiple is a capex-and-Reels debate",
    body: "Core ads can still grow with a healthier auction and Reels monetization. That is already in a lot of the tape. The stock will trade incremental capex against incremental AI-ad yield. We would own a capex scare if family-of-apps engagement holds. We would not own a re-rating that assumes Reality Labs is suddenly a rounding error with no cash drain. This is an ads compounder with a spending overlay. Underwrite the overlay.",
    sub_topic: "Technology",
    current_health: 24,
    authorUsername: "demo_kira_moss",
    hoursAgo: 61,
  },
  {
    title: "The last mile of disinflation is a labor story, not a goods story",
    body: "Goods deflation has done the easy work. The remaining CPI gap is housing and services, which means wages, quits, and the unemployment rate, not container rates. We would fade the first clean goods print that the market treats as mission accomplished. Duration can still work, but the path is choppier than a simple 'cuts are here' slogan. Position for a labor-market glide path, not a goods-led victory lap.",
    sub_topic: "Macro",
    current_health: 96,
    authorUsername: "demo_irene_wahl",
    hoursAgo: 9,
  },
  {
    title: "Treasury term premium: fade the first 25bp, not the cycle",
    body: "A single cut does not dissolve term premium if issuance stays heavy and the front end is already priced. We would sell the first celebratory rally in long duration and keep dry powder for a proper growth scare. The curve can steepen for the wrong reasons. That is not a reason to be structurally short duration; it is a reason to be tactical. The better expression is intermediates until the labor data forces the long end to do real work.",
    sub_topic: "Macro",
    current_health: 53,
    authorUsername: "demo_marcus_dale",
    hoursAgo: 16,
  },
  {
    title: "Dollar tightness and EM: fund the surplus names only",
    body: "A sticky dollar is not a blanket EM short. It is a screen. We want current-account surplus, credible local policy, and an export mix that is not just China-beta. The rest of the complex is a funding trade dressed up as a growth story. If the dollar breaks, those names will work too — later, and with worse risk/reward. Until then, be paid to wait in the surplus set.",
    sub_topic: "Macro",
    current_health: 67,
    authorUsername: "demo_sasha_kline",
    hoursAgo: 29,
  },
  {
    title: "Japan carry: the unwind is a process, not an event",
    body: "A higher Japanese policy rate and a less-suppressed JGB curve can pressure the global carry complex for quarters, not days. That does not mean a disorderly unwind is the base case. We would rather reduce the most crowded yen-funded expressions than run a binary short on global risk. Watch MoF rhetoric, real-rate differentials, and whether domestic allocators actually repatriate. This is a positioning story first. Trade it that way.",
    sub_topic: "Macro",
    current_health: 81,
    authorUsername: "demo_nora_weiss",
    hoursAgo: 19,
  },
  {
    title: "China property is still the constraint; policy is a floor, not a catalyst",
    body: "Stabilization packages can put a floor under the worst of the property complex. They do not restore a 2016-style credit impulse. We would own the exporters and the platforms that can grow without a property rebound, and we would treat onshore credit-sensitive cyclicals as trades, not as a structural overweight. The risk is not missing the first bounce. The risk is paying a recovery multiple for a balance-sheet workout.",
    sub_topic: "Macro",
    current_health: 35,
    authorUsername: "demo_rafael_dunn",
    hoursAgo: 44,
  },
  {
    title: "IG credit spreads: carry is fine; the asymmetry is not",
    body: "Investment-grade spreads are tight because the cycle has not broken. That is a statement about carry, not about convexity. We would rather be underweight spread duration and own higher-quality issuers than stretch for yield in BBB cyclicals. If the labor data rolls over, the first move is a gap, not a gentle widening. Keep dry powder. This is a market that pays you to wait, not to reach.",
    sub_topic: "Macro",
    current_health: 74,
    authorUsername: "demo_cyrus_ade",
    hoursAgo: 26,
  },
  {
    title: "Gold versus real rates: the bid is official-sector, not just real-yield math",
    body: "A simple real-rate framework still matters. It is no longer sufficient. Official-sector buying and a demand for unencumbered reserves have changed the residual. We would fade a spike that is only a real-rate squeeze. We would not fade a dip that is only a stronger-dollar day if central-bank demand is intact. Size gold as a portfolio hedge with a structural bid, not as a momentum commodity.",
    sub_topic: "Macro",
    current_health: 42,
    authorUsername: "demo_nara_quinn",
    hoursAgo: 55,
  },
  {
    title: "US housing: rates can ease and starts can still disappoint",
    body: "A lower mortgage rate helps affordability at the margin. It does not automatically unlock a starts cycle if lock-in, insurance costs, and labor keep the existing-home market frozen. We would rather own the names levered to repair, remodel, and scarce lots than a simple rates-down housing-beta basket. The first 50bp does more for sentiment than for volumes. Wait for listings, not for the first cut.",
    sub_topic: "Macro",
    current_health: 18,
    authorUsername: "demo_elio_voss",
    hoursAgo: 67,
  },
  {
    title: "Saudi spare capacity is the ceiling; US shale is the floor",
    body: "The oil tape is a corridor, not a trend, until one of those two constraints moves. We would fade both the $100 spike narrative and the structural-demand-death narrative. The tradable range is defined by OPEC+ reaction function on the way up and US shale response on the way down. Equities that only work outside that corridor are options, not core holdings. Prefer balance-sheet strength and buyback coverage inside the range.",
    sub_topic: "Energy",
    current_health: 109,
    authorUsername: "demo_cyrus_ade",
    hoursAgo: 7,
  },
  {
    title: "European gas storage is a weather option, not a structural short",
    body: "Storage looks comfortable until a late-winter draw or a supply interruption reopens the risk premium. We would not run a structural short on European gas-linked equities from a full-storage headline. We would also not pay a crisis multiple for a weather option. The cleaner book is the midstream and utility names that get paid to move and store molecules either way. Leave the directional gas bet to the curve.",
    sub_topic: "Energy",
    current_health: 38,
    authorUsername: "demo_owen_blake",
    hoursAgo: 21,
  },
  {
    title: "US power: interconnection queues are the constraint, not generation tech",
    body: "The bottleneck is not whether solar, gas, or nuclear can be built in theory. It is whether projects can get a queue position, a transformer, and a wire. That supports the owners of scarce interconnect and the equipment names tied to grid hardware. It is a slower, more political capex cycle than a simple data-center megawatt headline. Underwrite permitting and copper, not the press release.",
    sub_topic: "Energy",
    current_health: 72,
    authorUsername: "demo_yuna_park",
    hoursAgo: 14,
  },
  {
    title: "Oil majors' buybacks survive $70; the cut is in growth capex",
    body: "The integrated majors have already told the market what they will protect: the dividend and a base buyback. Growth projects slip first. That is not bearish for the equity if the market is still underwriting a growth-capex renaissance. We would own the names that can hold distributions at $70 and treat $90 as surplus, not as a new baseline. This is a cash-return sector again. Trade it that way.",
    sub_topic: "Energy",
    current_health: 16,
    authorUsername: "demo_elio_voss",
    hoursAgo: 44,
  },
  {
    title: "NextEra: regulated rate base is the core; the renewables multiple is the debate",
    body: "The utility can still compound rate base through transmission and generation that data-center load actually needs. The equity risk is paying a growth-utility multiple for a renewables development pipeline that still has to clear interconnection and offtake. We would own a development miss if the regulated story is intact. We would not own a re-rating that treats every megawatt announcement as already in the rate base. Underwrite the franchise, not the press release.",
    sub_topic: "Energy",
    current_health: 93,
    authorUsername: "demo_lina_moreau",
    hoursAgo: 10,
  },
  {
    title: "Cheniere: LNG contracted cash is the floor; Europe weather is the residual",
    body: "The contracted offtake book supports a durable distribution and buyback. Spot Europe and Asia residual volumes are the variance, not the thesis. We would accumulate on a weather-driven destocking scare. We would fade a spike that treats every cargo as a new structural tightness. This is a midstream-like cash-return name wearing a commodity beta. Price the contract book first.",
    sub_topic: "Energy",
    current_health: 64,
    authorUsername: "demo_amina_cole",
    hoursAgo: 30,
  },
  {
    title: "SLB: international activity is the cycle; US land is the drag you already know",
    body: "The better service tape is still international and offshore, not a US land re-acceleration. That supports the names with technology attach and a cleaner international mix. We would own a US-land miss if international bookings and digital attach hold. We would not own a North America beat as if the old shale cycle were back. Size it as a multi-year international capex cycle with a service-intensity overlay.",
    sub_topic: "Energy",
    current_health: 47,
    authorUsername: "demo_mira_chen",
    hoursAgo: 48,
  },
  {
    title: "Copper and grid hardware: the bottleneck is transformers, not the metal print",
    body: "A tighter copper balance helps the miners. The cleaner equity expression of the power-and-data-center build is still the equipment and interconnect names that can actually deliver transformers, switchgear, and wire. We would rather be early in the hardware queue than late in a copper squeeze that the market has already treated as a structural shortage. Underwrite lead times and backlog quality. Leave the pure metal beta to the curve.",
    sub_topic: "Energy",
    current_health: 21,
    authorUsername: "demo_jonas_reed",
    hoursAgo: 63,
  },
];
